import type { ValidationIssue } from "@/domain/project/validation";
import type { AppLocale } from "./translations";
import { formatTemplate } from "./translations";

const messages: Record<AppLocale, Record<string, string>> = {
  en: {
    NO_SCREENS: "Project must contain at least one screen.", INVALID_COMMAND: "Screen “{screen}” has an invalid command trigger.", EMPTY_CONTENT: "Screen “{screen}” has no message text or media.", INVALID_MEDIA_URL: "Screen “{screen}” has an invalid photo URL.", NO_BUTTONS: "Screen “{screen}” has no buttons.", EMPTY_BUTTON_TEXT: "An inline button on “{screen}” has no text.", MISSING_SCREEN_TARGET: "Button “{button}” points to a missing screen.", INVALID_CALLBACK_LENGTH: "Callback for “{button}” must be 1–64 UTF-8 bytes; current value is {bytes} bytes.", RESERVED_CALLBACK_PREFIX: "Callback for “{button}” uses reserved prefix {prefix}.", INVALID_URL: "Button “{button}” has an invalid HTTP/HTTPS URL.", DUPLICATE_COMMAND: "Command /{command} is assigned to multiple screens.", NO_START: "No /start command trigger exists.", UNREACHABLE_SCREEN: "Screen “{screen}” cannot be reached from a command entry point.", NO_ENTRY: "Screen “{screen}” has no incoming transition and no command trigger.", INLINE_REPLY_CONFLICT: "Screen “{screen}” cannot use an inline keyboard and change the bottom keyboard in the same message.", EMPTY_REPLY_KEYBOARD: "Bottom keyboard on “{screen}” is enabled but contains no buttons.", REPLY_OPTION_CONFLICT: "One-time and persistent bottom keyboard options cannot both be enabled on “{screen}”.", EMPTY_REPLY_BUTTON_TEXT: "A bottom keyboard button on “{screen}” has no text.", MISSING_REPLY_SCREEN_TARGET: "Bottom button “{button}” points to a missing screen.", INVALID_WEBAPP_URL: "Web App button “{button}” must use an HTTPS URL.", DUPLICATE_REPLY_NAV_TEXT: "Navigation text “{text}” is used by more than one bottom keyboard button.", INVALID_BOT_COMMAND: "Bot command “{command}” is invalid.", INVALID_BOT_COMMAND_DESCRIPTION: "Bot command /{command} needs a 1–256 character description.", DUPLICATE_BOT_COMMAND: "Bot command /{command} is duplicated.", EMPTY_MENU_BUTTON_TEXT: "Web App menu button text is required.", INVALID_MENU_WEBAPP_URL: "Web App menu button URL must use HTTPS."
  },
  ru: {
    NO_SCREENS: "В проекте должен быть хотя бы один экран.", INVALID_COMMAND: "У экрана «{screen}» некорректная команда.", EMPTY_CONTENT: "У экрана «{screen}» нет текста сообщения или медиа.", INVALID_MEDIA_URL: "У экрана «{screen}» некорректный URL изображения.", NO_BUTTONS: "У экрана «{screen}» нет кнопок.", EMPTY_BUTTON_TEXT: "У inline-кнопки на экране «{screen}» нет текста.", MISSING_SCREEN_TARGET: "Кнопка «{button}» ведёт на отсутствующий экран.", INVALID_CALLBACK_LENGTH: "Callback кнопки «{button}» должен занимать 1–64 байта UTF-8; сейчас {bytes}.", RESERVED_CALLBACK_PREFIX: "Callback кнопки «{button}» использует зарезервированный префикс {prefix}.", INVALID_URL: "У кнопки «{button}» некорректный HTTP/HTTPS URL.", DUPLICATE_COMMAND: "Команда /{command} назначена нескольким экранам.", NO_START: "Нет команды /start.", UNREACHABLE_SCREEN: "Экран «{screen}» недостижим из командной точки входа.", NO_ENTRY: "У экрана «{screen}» нет входящего перехода и команды.", INLINE_REPLY_CONFLICT: "Экран «{screen}» не может одновременно использовать inline-клавиатуру и менять нижнюю клавиатуру в одном сообщении.", EMPTY_REPLY_KEYBOARD: "Нижняя клавиатура экрана «{screen}» включена, но не содержит кнопок.", REPLY_OPTION_CONFLICT: "Одноразовый и постоянный режимы нижней клавиатуры нельзя включать одновременно на экране «{screen}».", EMPTY_REPLY_BUTTON_TEXT: "У кнопки нижней клавиатуры на экране «{screen}» нет текста.", MISSING_REPLY_SCREEN_TARGET: "Нижняя кнопка «{button}» ведёт на отсутствующий экран.", INVALID_WEBAPP_URL: "Web App кнопки «{button}» должен использовать HTTPS.", DUPLICATE_REPLY_NAV_TEXT: "Навигационный текст «{text}» используется несколькими нижними кнопками.", INVALID_BOT_COMMAND: "Команда бота «{command}» некорректна.", INVALID_BOT_COMMAND_DESCRIPTION: "Для команды /{command} нужно описание длиной 1–256 символов.", DUPLICATE_BOT_COMMAND: "Команда бота /{command} дублируется.", EMPTY_MENU_BUTTON_TEXT: "Для Web App кнопки меню нужен текст.", INVALID_MENU_WEBAPP_URL: "URL Web App кнопки меню должен использовать HTTPS."
  },
};

export function translateValidationIssue(issue: ValidationIssue, locale: AppLocale): string {
  return formatTemplate(messages[locale][issue.code] ?? issue.code, issue.params ?? {});
}
