"use client";

import { AlertTriangle, CheckCircle2, X, XCircle } from "lucide-react";
import type { ValidationIssue } from "@/domain/project/validation";
import { Button } from "@/components/ui/Button";
import { useProjectStore } from "@/store/project-store";
import { usePreferencesStore } from "@/store/preferences-store";
import { useTranslations } from "@/i18n/use-translations";
import { translateValidationIssue } from "@/i18n/validation-messages";
import { formatTemplate } from "@/i18n/translations";

export function ValidationPanel({ issues, onClose }: { issues: ValidationIssue[]; onClose: () => void }) {
  const t = useTranslations(); const locale = usePreferencesStore((state) => state.locale); const selectScreen = useProjectStore((state) => state.selectScreen); const selectInlineButton = useProjectStore((state) => state.selectInlineButton); const selectReplyButton = useProjectStore((state) => state.selectReplyButton); const project = useProjectStore((state) => state.project); const setMode = useProjectStore((state) => state.setMode);
  const errors = issues.filter((item) => item.severity === "error"); const warnings = issues.filter((item) => item.severity === "warning");
  function navigate(item: ValidationIssue) { if (!item.screenId) return; setMode("design"); if (item.buttonId) { const screen = project.screens.find((candidate) => candidate.id === item.screenId); if (item.buttonKind === "reply" && screen?.replyKeyboard.mode === "show") { const row = screen.replyKeyboard.config.rows.find((candidate) => candidate.buttons.some((button) => button.id === item.buttonId)); if (row) selectReplyButton(item.screenId, row.id, item.buttonId); else selectScreen(item.screenId); } else { const row = screen?.inlineKeyboard.find((candidate) => candidate.buttons.some((button) => button.id === item.buttonId)); if (row) selectInlineButton(item.screenId, row.id, item.buttonId); else selectScreen(item.screenId); } } else selectScreen(item.screenId); onClose(); }
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/55 backdrop-blur-sm" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div role="dialog" aria-modal="true" aria-label={t.validation.title} className="flex h-full w-full max-w-lg flex-col border-l border-slate-700 bg-slate-950 shadow-2xl"><div className="flex items-start justify-between border-b border-slate-800 p-5"><div><div className="text-lg font-semibold text-white">{t.validation.title}</div><div className="mt-1 text-sm text-slate-500">{formatTemplate(t.validation.summary, { errors: errors.length, warnings: warnings.length })}</div></div><Button className="h-8 w-8 p-0" onClick={onClose} aria-label={t.validation.close}><X size={15} /></Button></div><div className="min-h-0 flex-1 space-y-3 overflow-y-auto p-5">{issues.length === 0 ? <div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm text-emerald-300"><CheckCircle2 className="mb-2" />{t.validation.clean}</div> : issues.map((item) => <button key={item.id} onClick={() => navigate(item)} className={`w-full rounded-xl border p-3 text-left hover:brightness-110 ${item.severity === "error" ? "border-rose-500/30 bg-rose-500/10" : "border-amber-500/30 bg-amber-500/10"}`}><div className="flex gap-3">{item.severity === "error" ? <XCircle className="mt-0.5 shrink-0 text-rose-400" size={17} /> : <AlertTriangle className="mt-0.5 shrink-0 text-amber-400" size={17} />}<div><div className={`text-sm ${item.severity === "error" ? "text-rose-200" : "text-amber-200"}`}>{translateValidationIssue(item, locale)}</div><div className="mt-1 text-[11px] uppercase tracking-wide text-slate-600">{item.code}</div></div></div></button>)}</div></div></div>;
}
