import type { BotMenuButton, Project } from "../../domain/project/types";
import { hasBlockingErrors, normalizeCommand, validateProject } from "../../domain/project/validation";
import { buildScreenRoutes } from "./callbacks";
import { generateHandlers } from "./handlers";
import { generateInlineKeyboards, generateReplyKeyboards } from "./keyboards";
import { pyString } from "./templates";

export type GeneratedFile = { path: string; content: string };
export type GeneratedProject = { files: GeneratedFile[] };

function menuButtonExpression(menu: BotMenuButton): string {
  if (menu.type === "default") return "MenuButtonDefault()";
  if (menu.type === "webApp") return `MenuButtonWebApp(text=${pyString(menu.text)}, web_app=WebAppInfo(url=${pyString(menu.url)}))`;
  return "MenuButtonCommands()";
}

function generateBotFile(project: Project): string {
  const commands = project.botSettings.commands.map((command) => `        BotCommand(command=${pyString(normalizeCommand(command.command))}, description=${pyString(command.description)}),`).join("\n");
  return `import asyncio\n\nfrom aiogram import Bot, Dispatcher\nfrom aiogram.types import BotCommand, MenuButtonCommands, MenuButtonDefault, MenuButtonWebApp, WebAppInfo\n\nfrom config import BOT_TOKEN\nfrom handlers.screens import router\n\n\nasync def configure_bot(bot: Bot) -> None:\n    commands = [\n${commands}\n    ]\n    await bot.set_my_commands(commands)\n    await bot.set_chat_menu_button(menu_button=${menuButtonExpression(project.botSettings.menuButton)})\n\n\nasync def main() -> None:\n    bot = Bot(token=BOT_TOKEN)\n    await configure_bot(bot)\n    dp = Dispatcher()\n    dp.include_router(router)\n    await dp.start_polling(bot)\n\n\nif __name__ == \"__main__\":\n    asyncio.run(main())\n`;
}

export function generateAiogramProject(project: Project): GeneratedProject {
  const issues = validateProject(project);
  if (hasBlockingErrors(issues)) throw new Error(`Project contains ${issues.filter((item) => item.severity === "error").length} blocking validation error(s).`);
  const routes = buildScreenRoutes(project);
  const files: GeneratedFile[] = [
    { path: "generated_bot/bot.py", content: generateBotFile(project) },
    { path: "generated_bot/config.py", content: `import os\n\nfrom dotenv import load_dotenv\n\nload_dotenv()\n\nBOT_TOKEN = os.getenv(\"BOT_TOKEN\")\nif not BOT_TOKEN:\n    raise RuntimeError(\"BOT_TOKEN is missing. Copy .env.example to .env and add your Telegram bot token.\")\n` },
    { path: "generated_bot/handlers/__init__.py", content: "" },
    { path: "generated_bot/handlers/screens.py", content: generateHandlers(project, routes) },
    { path: "generated_bot/keyboards/__init__.py", content: "" },
    { path: "generated_bot/keyboards/inline.py", content: generateInlineKeyboards(project, routes) },
    { path: "generated_bot/keyboards/reply.py", content: generateReplyKeyboards(project) },
    { path: "generated_bot/.env.example", content: "BOT_TOKEN=YOUR_TELEGRAM_BOT_TOKEN\n" },
    { path: "generated_bot/requirements.txt", content: "aiogram>=3,<4\npython-dotenv>=1,<2\n" },
    { path: "generated_bot/README.md", content: `# Generated Telegram Bot\n\nThis project was generated by Telegram Bot Visual Builder.\n\n## Requirements\n\n- Python 3.11+\n\n## Run\n\n\`\`\`bash\npython -m venv .venv\n# Activate the virtual environment for your OS\npip install -r requirements.txt\ncp .env.example .env\n# Add BOT_TOKEN to .env\npython bot.py\n\`\`\`\n\nInline callbacks and bottom-keyboard text actions that require custom business logic are emitted as safe TODO stubs in \`handlers/screens.py\`. Bot commands and the Telegram chat menu button are configured on startup.\n` },
  ];
  return { files };
}
