import type { Project } from "../../domain/project/types";
import { validateProject, hasBlockingErrors } from "../../domain/project/validation";
import { buildScreenRoutes } from "./callbacks";
import { generateHandlers } from "./handlers";
import { generateKeyboards } from "./keyboards";

export type GeneratedFile = { path: string; content: string };
export type GeneratedProject = { files: GeneratedFile[] };

export function generateAiogramProject(project: Project): GeneratedProject {
  const issues = validateProject(project);
  if (hasBlockingErrors(issues)) {
    throw new Error(`Project contains ${issues.filter((item) => item.severity === "error").length} blocking validation error(s).`);
  }

  const routes = buildScreenRoutes(project);
  const files: GeneratedFile[] = [
    {
      path: "generated_bot/bot.py",
      content: `import asyncio\n\nfrom aiogram import Bot, Dispatcher\n\nfrom config import BOT_TOKEN\nfrom handlers.screens import router\n\n\nasync def main() -> None:\n    bot = Bot(token=BOT_TOKEN)\n    dp = Dispatcher()\n    dp.include_router(router)\n    await dp.start_polling(bot)\n\n\nif __name__ == "__main__":\n    asyncio.run(main())\n`,
    },
    {
      path: "generated_bot/config.py",
      content: `import os\n\nfrom dotenv import load_dotenv\n\nload_dotenv()\n\nBOT_TOKEN = os.getenv("BOT_TOKEN")\nif not BOT_TOKEN:\n    raise RuntimeError("BOT_TOKEN is missing. Copy .env.example to .env and add your Telegram bot token.")\n`,
    },
    { path: "generated_bot/handlers/__init__.py", content: "" },
    { path: "generated_bot/handlers/screens.py", content: generateHandlers(project, routes) },
    { path: "generated_bot/keyboards/__init__.py", content: "" },
    { path: "generated_bot/keyboards/screens.py", content: generateKeyboards(project, routes) },
    { path: "generated_bot/.env.example", content: "BOT_TOKEN=YOUR_TELEGRAM_BOT_TOKEN\n" },
    { path: "generated_bot/requirements.txt", content: "aiogram>=3,<4\npython-dotenv>=1,<2\n" },
    {
      path: "generated_bot/README.md",
      content: `# Generated Telegram Bot\n\nThis project was generated by Telegram Bot Visual Builder.\n\n## Requirements\n\n- Python 3.11+\n\n## Run\n\n\
\`\`\`bash\npython -m venv .venv\n# Activate the virtual environment for your OS\npip install -r requirements.txt\ncp .env.example .env\n# Add BOT_TOKEN to .env\npython bot.py\n\`\`\`\n\nCustom callback actions are generated as safe stubs in \`handlers/screens.py\`. Replace those TODO stubs with your application-specific business logic.\n`,
    },
  ];

  return { files };
}
